
EXTENSION_NAME=ext_ad_password_change

ZCS_LIB_JARS=\
	zimbracommon.jar	\
	zimbrastore.jar		\
	dom4j-1.5.2.jar

TOPDIR=../../
include $(TOPDIR)/common.mk
include $(ZIMBRA_BUILD_ROOT)/extensions-extra/zmpkg/mk/zcs-extension.mk
