VERSION=1.0.1.11
PACKAGE=vnc-ad-password-change
MAINTAINER=Stefan Sänger <stefan.saenger@vnc.biz>
SECTION=free/zcs-util
PRIORITY=optional
DEPENDS=
DESCRIPTION=ADPassword change extension
REDMINE_UPLOAD_PROJECT=vnc-ad-password-change
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
LAST_VERSION_TAG=vnc-ad-password-change-$(LAST_VERSION)
