VERSION=1.0.1.10
PACKAGE=vnc-ad-password-change
MAINTAINER=Dhaval Yoganandi <dhaval.yoganandi@vnc.biz>
SECTION=commercial/zcs-util
PRIORITY=optional
DEPENDS=
DESCRIPTION=ADPassword change extension
REDMINE_UPLOAD_PROJECT=vnc-ad-password-change
REDMINE_UPLOAD_URL=https://redmine.vnc.biz/redmine/
LAST_VERSION_TAG=vnc-ad-password-change-$(LAST_VERSION)
